- repo: https://github.com/ambv/black
  rev: stable
  hooks:
  - id: black
    language_version: python3.7
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: master
  hooks:
  - id: check-yaml
  - id: detect-private-key
  - id: trailing-whitespace
- repo: https://github.com/pycqa/flake8
  rev: master
  hooks:
  - id: flake8
    #additional_dependencies: [flake8-docstrings]
